#
# YAML
#
# Copyright 2022-2023 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.
#

include:
  - project: 'I0271_CI/I0271_Gitlab_Templates'
    file: '/templates/Multi-Module-Flow.gitlab-ci.yml'

---

multibuild:
  - name: Platform
    image: p0286-docker.forge.microej.com/sdk-idf_v5_0_1
    variables:
      MODULE_DIR: "ESP32-S3-DevKitC1-Xtensa-FreeRTOS-configuration"
      ANT_PROPERTIES: "-Dcom.microej.platformbuilder.bsp.build.enabled=true -Dcom.microej.platformbuilder.architecture.usage=eval -Dmmm.module.name=Platform -Dskip.publish=false"
      APPLY_FIRST_BSP_COMPILE_HOOKS: "true"
      GIT_SUBMODULE_STRATEGY: "recursive"

  - name: Platform-prod
    image: p0286-docker.forge.microej.com/sdk-idf_v5_0_1
    variables:
      MODULE_DIR: "ESP32-S3-DevKitC1-Xtensa-FreeRTOS-configuration"
      ANT_PROPERTIES: "-Dcom.microej.platformbuilder.bsp.build.enabled=true -Dcom.microej.platformbuilder.architecture.usage=prod -Dmmm.module.name=Platform-prod -Dskip.publish=false"
      APPLY_FIRST_BSP_COMPILE_HOOKS: "true"
      GIT_SUBMODULE_STRATEGY: "recursive"
